name: deploy website
on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'main'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install
        shell: bash
        run: yarn install
      - name: prisma
        shell: bash
        run: |
          # yarn prisma db push
          yarn prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: build
        shell: bash
        run: yarn next build

      - uses: amondnet/vercel-action@v20
        with:
          # GitHub Actions の Secrets で作成した値を参照する形で
          # Vercel デプロイ時に必要となる各種パラメタを設定する
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: "--prod" # Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./
